"""Writing a fictional airframe out as JSBSim XML (PHASE 16).

JSBSim ships with real aircraft definitions. **None of them are used here.** The
platform's rule is that every entity, airframe and parameter is fictional, and
loading a bundled model would break it on the first tick. So the adapter points
JSBSim at a data root that this module generates, containing exactly one
aircraft: the same invented airframe ``simulation/aircraft.py`` already
describes.

Generating rather than hand-writing the XML is what keeps the two physics
backends honest about each other. ``Simple6DOFModel`` and JSBSim read the *same*
``AircraftParameters`` — mass, inertia, reference geometry, every aerodynamic
coefficient — so a difference between the two is a difference between the
*models*, never between two airframes that drifted apart in separate files.

Two deliberate choices:

**Thrust is an external force, not an engine.** JSBSim's engine types each carry
their own spool-up, fuel flow and altitude lapse. Our fictional platform's
thrust model is ``max_thrust_n * throttle`` along body X, and an external
reaction reproduces exactly that. Inventing a turbine to wrap it would add
fiction that the other backend does not have.

**Lift and drag are tables.** ``Cl`` saturates at ``cl_max`` to model stall, and
JSBSim has no clamp inside a product. A table on angle of attack expresses the
saturation directly and is the idiomatic form. ``Cd = cd_0 + k*Cl^2`` is
tabulated from the same clamped ``Cl``, so the two stay consistent by
construction.

Everything emitted here is invented for simulation research. It models flight
and nothing else: there is no weapon, store, targeting or engagement modelling
in any of it.
"""

from __future__ import annotations

import hashlib
import math
from dataclasses import asdict
from pathlib import Path

from simulation.aircraft import AircraftParameters

# JSBSim works internally in imperial units, and an external force is declared
# in pounds. One pound-force in newtons, exactly as defined.
NEWTONS_PER_LBF = 4.4482216152605

# Angle-of-attack breakpoints for the lift and drag tables, in degrees. The
# range runs well past stall so a mishandled aircraft still gets a defined
# coefficient rather than an extrapolation off the end of the table.
_ALPHA_MIN_DEG = -30.0
_ALPHA_MAX_DEG = 30.0
_ALPHA_STEP_DEG = 1.0


def _alpha_breakpoints() -> list[float]:
    count = round((_ALPHA_MAX_DEG - _ALPHA_MIN_DEG) / _ALPHA_STEP_DEG) + 1
    return [_ALPHA_MIN_DEG + i * _ALPHA_STEP_DEG for i in range(count)]


def lift_coefficient(params: AircraftParameters, alpha_rad: float) -> float:
    """``Cl`` at an angle of attack, clamped at the stall ceiling.

    The same expression ``Simple6DOFModel`` evaluates analytically.
    """
    cl = params.cl_0 + params.cl_alpha * alpha_rad
    return max(-params.cl_max, min(params.cl_max, cl))


def drag_coefficient(params: AircraftParameters, alpha_rad: float) -> float:
    """``Cd = cd_0 + k * Cl^2``, from the clamped ``Cl``."""
    cl = lift_coefficient(params, alpha_rad)
    return params.cd_0 + params.induced_drag_k * cl * cl


def _table(rows: list[tuple[float, float]]) -> str:
    body = "\n".join(f"        {a:.6f}  {v:.6f}" for a, v in rows)
    return (
        "     <table>\n"
        '      <independentVar lookup="row">aero/alpha-deg</independentVar>\n'
        "      <tableData>\n"
        f"{body}\n"
        "      </tableData>\n"
        "     </table>"
    )


def airframe_xml(params: AircraftParameters) -> str:
    """The JSBSim aircraft definition for one fictional platform."""
    alphas = _alpha_breakpoints()
    lift_rows = [(a, lift_coefficient(params, math.radians(a))) for a in alphas]
    drag_rows = [(a, drag_coefficient(params, math.radians(a))) for a in alphas]

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by backend/simulation/jsbsim_airframe.py — do not edit by hand.

  A FICTIONAL airframe, invented for simulation research. It is not a model of
  any real aircraft, and it models flight only: no weapon, store, targeting or
  engagement behaviour is described here or anywhere else in this platform.

  Every number below comes from AircraftParameters in
  backend/simulation/aircraft.py, so this airframe and the one flown by
  Simple6DOFModel are the same invented platform.
-->
<fdm_config name="{params.name}" version="2.0" release="ALPHA">

 <fileheader>
  <author>AIFCS — generated</author>
  <description>Fictional research airframe {params.name}</description>
 </fileheader>

 <metrics>
  <wingarea unit="M2">{params.wing_area_m2:.6f}</wingarea>
  <wingspan unit="M">{params.wing_span_m:.6f}</wingspan>
  <chord unit="M">{params.mean_chord_m:.6f}</chord>
  <!-- Aerodynamic reference point, centre of gravity and visual reference all
       sit at the origin: the fictional platform is modelled as a point mass
       with a diagonal inertia tensor, exactly as the other backend treats it. -->
  <location name="AERORP" unit="M"><x>0.0</x><y>0.0</y><z>0.0</z></location>
  <location name="EYEPOINT" unit="M"><x>0.0</x><y>0.0</y><z>0.0</z></location>
  <location name="VRP" unit="M"><x>0.0</x><y>0.0</y><z>0.0</z></location>
 </metrics>

 <mass_balance>
  <ixx unit="KG*M2">{params.inertia_xx:.6f}</ixx>
  <iyy unit="KG*M2">{params.inertia_yy:.6f}</iyy>
  <izz unit="KG*M2">{params.inertia_zz:.6f}</izz>
  <emptywt unit="KG">{params.mass_kg:.6f}</emptywt>
  <location name="CG" unit="M"><x>0.0</x><y>0.0</y><z>0.0</z></location>
 </mass_balance>

 <!-- No landing gear: every scenario starts and stays airborne. -->
 <ground_reactions/>

 <!-- No engine. Thrust is an external force along body X, set each step from
      max_thrust_n * throttle, which is the thrust model the other backend
      uses. An engine would add spool-up and altitude lapse that only one of
      the two backends had. -->
 <propulsion/>

 <external_reactions>
  <force name="thrust" frame="BODY" unit="LBS">
   <location unit="M"><x>0.0</x><y>0.0</y><z>0.0</z></location>
   <direction><x>1.0</x><y>0.0</y><z>0.0</z></direction>
  </force>
 </external_reactions>

 <!-- The demands arrive already validated, envelope-protected and rate-limited
      by the flight controller, so the control path here is a pass-through.
      Putting a second set of limits in the airframe would hide what the safety
      layer did. -->
 <flight_control name="{params.name} passthrough">
  <channel name="Surfaces">
   <pure_gain name="fcs/aileron-pos-norm">
    <input>fcs/aileron-cmd-norm</input><gain>1.0</gain>
    <clipto><min>-1.0</min><max>1.0</max></clipto>
   </pure_gain>
   <pure_gain name="fcs/elevator-pos-norm">
    <input>fcs/elevator-cmd-norm</input><gain>1.0</gain>
    <clipto><min>-1.0</min><max>1.0</max></clipto>
   </pure_gain>
   <pure_gain name="fcs/rudder-pos-norm">
    <input>fcs/rudder-cmd-norm</input><gain>1.0</gain>
    <clipto><min>-1.0</min><max>1.0</max></clipto>
   </pure_gain>
  </channel>
 </flight_control>

 <aerodynamics>

  <axis name="LIFT">
   <function name="aero/force/lift">
    <description>Lift, saturating at cl_max to model stall</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
{_table(lift_rows)}
    </product>
   </function>
  </axis>

  <axis name="DRAG">
   <function name="aero/force/drag">
    <description>Parasite plus induced drag, from the same clamped Cl</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
{_table(drag_rows)}
    </product>
   </function>
  </axis>

  <axis name="SIDE">
   <function name="aero/force/side_beta">
    <description>Restoring side force from sideslip</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>aero/beta-rad</property>
     <value>{params.cy_beta:.6f}</value>
    </product>
   </function>
  </axis>

  <axis name="ROLL">
   <function name="aero/moment/roll_aileron">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>fcs/aileron-pos-norm</property>
     <value>{params.cl_aileron:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/roll_beta">
    <description>Dihedral effect</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>aero/beta-rad</property>
     <value>{params.cl_beta:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/roll_damp">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>velocities/p-aero-rad_sec</property>
     <property>aero/bi2vel</property>
     <value>{params.clp:.6f}</value>
    </product>
   </function>
  </axis>

  <axis name="PITCH">
   <function name="aero/moment/pitch_trim">
    <description>Sets the trim angle of attack</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/cbarw-ft</property>
     <value>{params.cm_0:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/pitch_alpha">
    <description>Static longitudinal stability</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/cbarw-ft</property>
     <property>aero/alpha-rad</property>
     <value>{params.cm_alpha:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/pitch_elevator">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/cbarw-ft</property>
     <property>fcs/elevator-pos-norm</property>
     <value>{params.cm_elevator:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/pitch_damp">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/cbarw-ft</property>
     <property>velocities/q-aero-rad_sec</property>
     <property>aero/ci2vel</property>
     <value>{params.cmq:.6f}</value>
    </product>
   </function>
  </axis>

  <axis name="YAW">
   <function name="aero/moment/yaw_beta">
    <description>Weathercock stability</description>
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>aero/beta-rad</property>
     <value>{params.cn_beta:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/yaw_rudder">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>fcs/rudder-pos-norm</property>
     <value>{params.cn_rudder:.6f}</value>
    </product>
   </function>
   <function name="aero/moment/yaw_damp">
    <product>
     <property>aero/qbar-psf</property>
     <property>metrics/Sw-sqft</property>
     <property>metrics/bw-ft</property>
     <property>velocities/r-aero-rad_sec</property>
     <property>aero/bi2vel</property>
     <value>{params.cnr:.6f}</value>
    </product>
   </function>
  </axis>

 </aerodynamics>
</fdm_config>
"""


def airframe_hash(params: AircraftParameters) -> str:
    """A short digest of the parameters an airframe file was generated from.

    The adapter regenerates a file whose digest no longer matches, so editing
    ``AircraftParameters`` can never leave a stale airframe on disk flying a
    platform the rest of the system has stopped describing.
    """
    payload = repr(sorted(asdict(params).items())).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def write_data_root(root: Path, airframes: dict[str, AircraftParameters]) -> list[Path]:
    """Write a JSBSim data root containing only these fictional airframes.

    Returns the files written or refreshed. A file whose digest already matches
    is left alone, so repeated starts do not rewrite it.
    """
    written: list[Path] = []
    for name, params in sorted(airframes.items()):
        directory = root / "aircraft" / name
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{name}.xml"
        stamp = directory / f"{name}.sha256"
        digest = airframe_hash(params)

        if path.exists() and stamp.exists() and stamp.read_text().strip() == digest:
            continue

        path.write_text(airframe_xml(params), encoding="utf-8")
        stamp.write_text(digest, encoding="utf-8")
        written.append(path)
    return written
