"""JSBSim as a swappable physics backend (PHASE 16).

``Simple6DOFModel`` is a compact Newton-Euler model written for this platform.
JSBSim is an established open-source flight dynamics model. Both satisfy the
same ``Integrator`` protocol, so the engine does not know or care which one is
advancing the world — which is the point of having declared that protocol back
in PHASE 1.

**The platform works without JSBSim.** It is an optional dependency. Asking for
it when it is not installed produces a message naming the package to install,
the subsystem registry reports the backend as unavailable, and the default
backend goes on flying. Nothing silently degrades and nothing pretends.

**No real aircraft is ever loaded.** JSBSim ships definitions for real aircraft;
the adapter points it at a data root generated by ``jsbsim_airframe.py``
containing only this platform's invented airframes. The bundled models are never
on the search path.

Three boundaries the adapter has to cross
-----------------------------------------

**Round earth to flat plane.** JSBSim positions a vehicle geodetically; the
world state is a local tangent plane in metres. The adapter converts through the
WGS84 radii of curvature at a reference latitude. Over a scenario's tens of
kilometres the mapping is accurate to well under a metre, which
``test_jsbsim.py`` measures rather than assumes.

**Its atmosphere, not ours.** JSBSim models a standard atmosphere, so density
falls with altitude; ``Simple6DOFModel`` uses the constant from
``configs/simulation.yaml``. At 6 km that is 0.66 against 1.225 kg/m3, so the
same airframe at the same throttle trims differently under the two backends.
That is a real difference between the models and is left visible instead of
being papered over — the agents fly closed-loop through the flight controller
and trim themselves either way.

**Truth stays authoritative.** JSBSim holds its own internal state, which makes
it the one component that could drift away from the world state. So the adapter
remembers exactly what it last wrote to each entity; if the truth state no
longer matches, something upstream moved the aircraft — a reset, an out-of-
bounds clamp, a scenario reload — and JSBSim is re-initialised from the world
rather than the other way round. The engine's truth is never overwritten by a
backend's private idea of where things are.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from core.logging_config import get_logger
from core.world_state import EntityState, EntityStatus, WorldState
from simulation.aircraft import FICTIONAL_AIRCRAFT, get_aircraft
from simulation.jsbsim_airframe import NEWTONS_PER_LBF, write_data_root
from simulation.physics import euler_from_quat, quat_from_euler

log = get_logger("physics.jsbsim")

FEET_PER_METRE = 1.0 / 0.3048

INSTALL_HINT = (
    "The JSBSim physics backend is not installed. Install it with:\n"
    "    pip install jsbsim\n"
    "or keep physics.backend set to simple_6dof in configs/simulation.yaml."
)

# WGS84. Used only to map the local tangent plane onto JSBSim's geodetic model.
_WGS84_A = 6378137.0
_WGS84_F = 1.0 / 298.257223563
_WGS84_E2 = _WGS84_F * (2.0 - _WGS84_F)


class JSBSimUnavailableError(RuntimeError):
    """Raised when the JSBSim backend is requested but the package is absent."""


def jsbsim_available() -> bool:
    """Whether the JSBSim package can be imported."""
    try:
        import jsbsim  # noqa: F401
    except ImportError:
        return False
    return True


def jsbsim_version() -> str | None:
    """The installed JSBSim version, or None when it is not installed."""
    try:
        import jsbsim
    except ImportError:
        return None
    version = getattr(jsbsim, "__version__", None)
    return str(version) if version else "unknown"


def _require_jsbsim() -> Any:
    # JSBSim prints a banner to stdout every time an FGFDMExec is constructed,
    # which would interleave with this platform's structured JSON logs once per
    # aircraft. JSBSim reads this variable at import, so it has to be set first.
    os.environ.setdefault("JSBSIM_DEBUG", "0")
    try:
        import jsbsim
    except ImportError as exc:  # pragma: no cover - only without the package
        raise JSBSimUnavailableError(INSTALL_HINT) from exc
    return jsbsim


@dataclass(frozen=True)
class GeodeticReference:
    """Where the flat world plane is pinned on the geodetic model.

    Fictional by default: the origin of the plane sits on the equator at the
    prime meridian. A scenario describes positions in metres and nothing in the
    platform depends on the plane being anywhere in particular.
    """

    latitude_deg: float = 0.0
    longitude_deg: float = 0.0

    @property
    def _radii(self) -> tuple[float, float]:
        """Meridional and prime-vertical radii of curvature at the reference."""
        lat = math.radians(self.latitude_deg)
        s = math.sin(lat)
        w = math.sqrt(1.0 - _WGS84_E2 * s * s)
        meridional = _WGS84_A * (1.0 - _WGS84_E2) / (w * w * w)
        prime_vertical = _WGS84_A / w
        return meridional, prime_vertical

    def to_geodetic(self, east_m: float, north_m: float) -> tuple[float, float]:
        """Plane metres to (latitude, longitude) in degrees."""
        meridional, prime_vertical = self._radii
        lat = self.latitude_deg + math.degrees(north_m / meridional)
        lon = self.longitude_deg + math.degrees(
            east_m / (prime_vertical * math.cos(math.radians(self.latitude_deg)))
        )
        return lat, lon

    def to_plane(self, latitude_deg: float, longitude_deg: float) -> tuple[float, float]:
        """(latitude, longitude) in degrees back to plane metres (east, north)."""
        meridional, prime_vertical = self._radii
        north = math.radians(latitude_deg - self.latitude_deg) * meridional
        east = (
            math.radians(longitude_deg - self.longitude_deg)
            * prime_vertical
            * math.cos(math.radians(self.latitude_deg))
        )
        return east, north


@dataclass
class _Vehicle:
    """One entity's JSBSim instance and the state the adapter last wrote."""

    fdm: Any
    airframe: str
    position: np.ndarray
    velocity: np.ndarray
    quaternion: np.ndarray


class JSBSimAdapter:
    """Advances the world with JSBSim, one FDM instance per entity.

    JSBSim models a single vehicle, so a formation is a set of instances. They
    share no state: the interaction between aircraft in this platform is
    sensing, datalink and coordination, never aerodynamic.
    """

    name = "jsbsim"

    def __init__(
        self,
        data_root: Path,
        reference: GeodeticReference | None = None,
        airframes: dict[str, Any] | None = None,
    ) -> None:
        self._jsbsim = _require_jsbsim()
        self.data_root = Path(data_root)
        self.reference = reference or GeodeticReference()
        self._airframes = dict(airframes or FICTIONAL_AIRCRAFT)
        self._vehicles: dict[str, _Vehicle] = {}

        written = write_data_root(self.data_root, self._airframes)
        log.info(
            "jsbsim data root ready",
            extra={
                "event": "JSBSIM_ROOT_READY",
                "root": str(self.data_root),
                "airframes": sorted(self._airframes),
                "regenerated": [p.name for p in written],
            },
        )

    # ------------------------------------------------------------- lifecycle

    def reset(self) -> None:
        """Drop every FDM instance. The next tick rebuilds them from truth."""
        self._vehicles.clear()

    def status(self) -> dict[str, Any]:
        return {
            "backend": self.name,
            "version": jsbsim_version(),
            "data_root": str(self.data_root),
            "airframes": sorted(self._airframes),
            "vehicles": len(self._vehicles),
            "reference": {
                "latitude_deg": self.reference.latitude_deg,
                "longitude_deg": self.reference.longitude_deg,
            },
            "notice": (
                "Fictional airframes generated from AircraftParameters. "
                "JSBSim's bundled aircraft are never loaded."
            ),
        }

    # ------------------------------------------------------------- integrate

    def integrate(self, world: WorldState, dt: float) -> None:
        live = {e.id for e in world.entities.values() if e.status is EntityStatus.ACTIVE}
        for gone in set(self._vehicles) - live:
            del self._vehicles[gone]

        for entity in world.entities.values():
            if entity.status is not EntityStatus.ACTIVE:
                continue
            self._advance_entity(entity, dt, world)

    def _advance_entity(self, entity: EntityState, dt: float, world: WorldState) -> None:
        vehicle = self._vehicles.get(entity.id)
        airframe = self._airframe_name(entity)

        # Re-initialise when the truth state was written by something other than
        # this adapter, or when the entity changed airframe.
        if (
            vehicle is None
            or vehicle.airframe != airframe
            or not np.array_equal(vehicle.position, entity.position)
            or not np.array_equal(vehicle.velocity, entity.velocity)
            or not np.array_equal(vehicle.quaternion, entity.attitude_quaternion)
        ):
            vehicle = self._build_vehicle(entity, airframe, dt)
            self._vehicles[entity.id] = vehicle

        fdm = vehicle.fdm
        controls = entity.controls.clamped()
        params = get_aircraft(airframe)

        fdm["fcs/aileron-cmd-norm"] = controls.aileron
        fdm["fcs/elevator-cmd-norm"] = controls.elevator
        fdm["fcs/rudder-cmd-norm"] = controls.rudder
        # Thrust along body X, in pounds: the same max_thrust_n * throttle the
        # other backend applies.
        fdm["external_reactions/thrust/magnitude"] = params.max_thrust_n * controls.throttle / NEWTONS_PER_LBF

        if not fdm.run():
            entity.status = EntityStatus.DISABLED
            entity.metadata["physics_error"] = "JSBSim refused to advance the vehicle"
            entity.velocity[:] = 0.0
            entity.angular_velocity[:] = 0.0
            self._vehicles.pop(entity.id, None)
            return

        self._write_back(entity, vehicle)

    # ---------------------------------------------------------------- detail

    def _airframe_name(self, entity: EntityState) -> str:
        declared = str(entity.metadata.get("type", ""))
        return declared if declared in self._airframes else "fictional_aircraft"

    def _build_vehicle(self, entity: EntityState, airframe: str, dt: float) -> _Vehicle:
        fdm = self._jsbsim.FGFDMExec(str(self.data_root))
        # JSBSim is chatty on stdout; the platform logs structurally instead.
        fdm.set_debug_level(0)
        if not fdm.load_model(airframe):
            raise JSBSimUnavailableError(
                f"JSBSim could not load the generated airframe {airframe!r} from {self.data_root}"
            )
        fdm.set_dt(dt)

        east, north, up = (float(v) for v in entity.position)
        latitude, longitude = self.reference.to_geodetic(east, north)
        roll, pitch, yaw = (float(v) for v in euler_from_quat(entity.attitude_quaternion))

        # Velocity is supplied in NED, so the initial condition does not depend
        # on the attitude being consistent with the velocity vector.
        velocity_east, velocity_north, velocity_up = (float(v) for v in entity.velocity)

        fdm["ic/lat-gc-deg"] = latitude
        fdm["ic/long-gc-deg"] = longitude
        fdm["ic/h-sl-ft"] = up * FEET_PER_METRE
        fdm["ic/vn-fps"] = velocity_north * FEET_PER_METRE
        fdm["ic/ve-fps"] = velocity_east * FEET_PER_METRE
        fdm["ic/vd-fps"] = -velocity_up * FEET_PER_METRE
        fdm["ic/phi-rad"] = roll
        fdm["ic/theta-rad"] = pitch
        fdm["ic/psi-true-rad"] = yaw

        if not fdm.run_ic():  # pragma: no cover - JSBSim rejects only bad ICs
            raise JSBSimUnavailableError(f"JSBSim rejected the initial condition for {entity.id}")

        # Body rates are not an initial-condition property; set them directly.
        rates = entity.angular_velocity
        fdm["velocities/p-rad_sec"] = float(rates[0])
        fdm["velocities/q-rad_sec"] = float(rates[1])
        fdm["velocities/r-rad_sec"] = float(rates[2])

        return _Vehicle(
            fdm=fdm,
            airframe=airframe,
            position=entity.position.copy(),
            velocity=entity.velocity.copy(),
            quaternion=entity.attitude_quaternion.copy(),
        )

    def _write_back(self, entity: EntityState, vehicle: _Vehicle) -> None:
        fdm = vehicle.fdm

        east, north = self.reference.to_plane(
            float(fdm["position/lat-gc-deg"]), float(fdm["position/long-gc-deg"])
        )
        up = float(fdm["position/h-sl-meters"])

        velocity_north = float(fdm["velocities/v-north-fps"]) / FEET_PER_METRE
        velocity_east = float(fdm["velocities/v-east-fps"]) / FEET_PER_METRE
        velocity_down = float(fdm["velocities/v-down-fps"]) / FEET_PER_METRE

        roll = float(fdm["attitude/phi-rad"])
        pitch = float(fdm["attitude/theta-rad"])
        yaw = float(fdm["attitude/psi-rad"])

        rates = np.array(
            [
                float(fdm["velocities/p-rad_sec"]),
                float(fdm["velocities/q-rad_sec"]),
                float(fdm["velocities/r-rad_sec"]),
            ]
        )

        position = np.array([east, north, up])
        velocity = np.array([velocity_east, velocity_north, -velocity_down])

        # Same guard as the other backend: a diverged solution freezes the
        # entity rather than letting NaN spread through the world state.
        if not (
            np.all(np.isfinite(position)) and np.all(np.isfinite(velocity)) and np.all(np.isfinite(rates))
        ):
            entity.status = EntityStatus.DISABLED
            entity.metadata["physics_error"] = "non-finite state from JSBSim"
            entity.velocity[:] = 0.0
            entity.angular_velocity[:] = 0.0
            self._vehicles.pop(entity.id, None)
            return

        # The quaternion is rebuilt with this platform's own convention rather
        # than taken from JSBSim, so every consumer of attitude keeps reading
        # the same thing it always has.
        quaternion = quat_from_euler(roll, pitch, yaw)

        entity.position[:] = position
        entity.velocity[:] = velocity
        entity.attitude_quaternion[:] = quaternion
        entity.angular_velocity[:] = rates
        entity.orientation[:] = euler_from_quat(quaternion)

        vehicle.position = entity.position.copy()
        vehicle.velocity = entity.velocity.copy()
        vehicle.quaternion = entity.attitude_quaternion.copy()
